// components/ui/AiBadge.tsx
//
// Small visual marker required by EU AI Act Art. 52 — users must know when
// they're looking at AI-generated output. Attach to any anomaly explanation,
// briefing, recommendation, budget suggestion, invoice extraction, or
// notebook generation that came out of a Claude call.
//
// Two variants:
//   <AiBadge />              — subtle purple "AI" pill for use alongside content
//   <AiBadge variant="block" tooltip="..." /> — larger banner for whole-section labelling

interface AiBadgeProps {
  variant?: 'pill' | 'block'
  tooltip?: string
  label?: string
}

export function AiBadge({ variant = 'pill', tooltip, label }: AiBadgeProps) {
  const defaultTooltip = 'Generated by AI. Treat as a suggestion for human review — not a regulated financial or legal output.'
  const title = tooltip ?? defaultTooltip

  if (variant === 'block') {
    return (
      <div title={title} style={{
        display: 'inline-flex', alignItems: 'center', gap: 6,
        padding: '4px 10px', background: '#ede9fe', color: '#6d28d9',
        border: '1px solid #ddd6fe', borderRadius: 6,
        fontSize: 11, fontWeight: 700, letterSpacing: '.04em',
      }}>
        <span aria-hidden="true">✦</span>
        <span>{label ?? 'AI-generated — review before acting'}</span>
      </div>
    )
  }

  return (
    <span title={title} style={{
      display: 'inline-flex', alignItems: 'center', gap: 3,
      padding: '1px 6px', background: '#ede9fe', color: '#6d28d9',
      borderRadius: 4, fontSize: 10, fontWeight: 700, letterSpacing: '.04em',
      verticalAlign: 'middle' as const,
    }}>
      <span aria-hidden="true">✦</span>
      <span>{label ?? 'AI'}</span>
    </span>
  )
}
