// lib/reports/margin-docx.ts
//
// Word (.docx) renderer for the margin report — same MarginReportSpec the
// PDF uses, different output. Uses the `docx` library (pure JS).

import {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  Table, TableRow, TableCell, WidthType, AlignmentType, BorderStyle,
} from 'docx'
import type { MarginReportSpec, MarginMonth } from '@/lib/reports/margin-report'

const INK = '3A3550', LAV = '7D6CC9', MUTED = '6B6680', GREEN = '477F60', ROSE = 'B0454E'
const kr = (n: number) => `${Math.round(n).toLocaleString('en-GB')} kr`
const marginColor = (m: number) => (m >= 10 ? GREEN : m >= 5 ? INK : ROSE)

function cell(text: string, opts: { bold?: boolean; color?: string; align?: any; header?: boolean } = {}) {
  return new TableCell({
    shading: opts.header ? { fill: 'F4F2FB' } : undefined,
    children: [new Paragraph({
      alignment: opts.align ?? AlignmentType.LEFT,
      children: [new TextRun({ text, bold: opts.bold, color: opts.color, size: 18 })],
    })],
  })
}

export async function renderMarginDocx(spec: MarginReportSpec): Promise<Buffer> {
  const a = spec.averages
  const headerRow = new TableRow({ children: [
    cell('Month', { header: true, bold: true }),
    cell('Revenue', { header: true, bold: true, align: AlignmentType.RIGHT }),
    cell('Food %', { header: true, bold: true, align: AlignmentType.RIGHT }),
    cell('Labour %', { header: true, bold: true, align: AlignmentType.RIGHT }),
    cell('Net margin', { header: true, bold: true, align: AlignmentType.RIGHT }),
  ]})
  const dataRows = spec.months.map((m: MarginMonth) => new TableRow({ children: [
    cell(`${m.label}${m.is_anomaly ? '  *' : ''}`, { color: m.is_anomaly ? MUTED : INK }),
    cell(kr(m.revenue), { align: AlignmentType.RIGHT }),
    cell(`${m.food_pct}%`, { align: AlignmentType.RIGHT }),
    cell(`${m.labour_pct}%`, { align: AlignmentType.RIGHT }),
    cell(`${m.margin_pct}%`, { align: AlignmentType.RIGHT, bold: true, color: m.is_anomaly ? MUTED : marginColor(m.margin_pct) }),
  ]}))

  const recs = spec.recommendations.flatMap((r, i) => ([
    new Paragraph({ spacing: { before: 140 }, children: [new TextRun({ text: `${i + 1}. ${r.title}`, bold: true, size: 20, color: INK })] }),
    ...(r.detail ? [new Paragraph({ children: [new TextRun({ text: r.detail, size: 19, color: MUTED })] })] : []),
  ]))

  const doc = new Document({
    sections: [{
      children: [
        new Paragraph({ children: [new TextRun({ text: 'COMMANDCENTER', bold: true, color: LAV, size: 16, characterSpacing: 40 })] }),
        new Paragraph({ heading: HeadingLevel.TITLE, children: [new TextRun({ text: 'Margin Report', color: INK })] }),
        new Paragraph({ children: [new TextRun({ text: `${spec.business_name}   ·   ${spec.period_label}`, color: MUTED, size: 20 })] }),

        new Paragraph({ spacing: { before: 200 }, children: [new TextRun({
          text: `Net margin (avg): ${a.margin_pct}%      Food: ${a.food_pct}%      Labour: ${a.labour_pct}%      Revenue/month: ${kr(a.revenue)}`,
          bold: true, size: 20, color: INK,
        })] }),

        new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 240 }, children: [new TextRun({ text: 'Summary', color: INK })] }),
        new Paragraph({ children: [new TextRun({ text: spec.executive_summary, size: 20, color: INK })] }),

        new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 240 }, children: [new TextRun({ text: 'Monthly margin trend', color: INK })] }),
        new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [headerRow, ...dataRows],
          borders: { top: { style: BorderStyle.SINGLE, size: 1, color: 'E6E3F0' }, bottom: { style: BorderStyle.SINGLE, size: 1, color: 'E6E3F0' }, left: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' }, right: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' }, insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: 'F0EEF8' }, insideVertical: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' } },
        }),
        ...(spec.anomaly_count > 0 ? [new Paragraph({ spacing: { before: 80 }, children: [new TextRun({
          text: `* ${spec.anomaly_count} month(s) flagged as a data anomaly and excluded from the averages — worth reviewing in Fortnox.`,
          italics: true, size: 16, color: MUTED,
        })] })] : []),

        new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 280 }, children: [new TextRun({ text: 'Recommendations to improve margin', color: INK })] }),
        ...recs,

        new Paragraph({ spacing: { before: 320 }, children: [new TextRun({
          text: `Figures sourced from your Fortnox financial data${spec.ai_used ? ' · narrative generated by CommandCenter AI' : ''}.  Generated ${new Date(spec.generated_at).toLocaleDateString('en-GB')}.`,
          size: 15, color: MUTED,
        })] }),
      ],
    }],
  })
  return Packer.toBuffer(doc) as unknown as Promise<Buffer>
}
